version: '3.9'

services:
  app:
    build:
      # builds the docker file inside our current directory or root directory
      context: .
      args:
        - DEV=true
    ports:
      # maps the port 8000 in our local machine to port 8000 in docker container
      - '8000:8000'
    volumes:
      # maps directory from our system to docker container while implements sync mechanism
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
